---
title: "Gov 50 Final Project"
author: "Jack Holland"
description: "My final project in Gov50!"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

What marks the difference between a straight-ticket voter and a split-ticket one? Are there certain demographic variables that put people at a higher propensity to engage in split-ticket voting behavior? How does political history and incumbency status contribute to this same phenomenon? Through data visualization and cross tab analysis, I plan to find answers to these questions, as well as novel ways to demonstrate ticket splitting via data. I hypothesize that many of the factors leading to the country's most pressing political cleavages-college education, income, and political participation-all have a hand in leading voters to split their votes in an increasingly formulated fashion. I expect that heightened measures for each of these variables all contribute to ticket splitting behavior, and vice versa. The scope of this study will be limited to a few specific regions of the country, namely New England, Georgia, Texas, and Wisconsin. Each of these states has a unique political history in regards to ticket splitting and aside from it. My analysis will come from the 2020 Election, senate elections, and lower state legislatures. Voters will be coded 1 for 'ticket splitters' and 0 for straight ticket voters. Splitting these groups and taking advantage of demogrpahic data, as well as precinct data, I hope to find meaningful differences between these groups' composition and behavior.